name: CustomCore
version: 1.0.0
author: RTGTeam
description: People has been dreaming for ages, now its a reality!
main: IGTheCore\Core\ServerCore
api: [2.0.0, 2.1.0]
commands:
  tp:
    description: "Teleport to a Player!"
  fly:
    description: "Toggle Fly mode!"
  gm:
    description: "GM help"
  gmc:
    description: "GameMode C!"
  gms:
    description: "GameMode S!"
  playerinfo:
    description: "Player Info!"
